---
Name: metatag_advanced_routes
After: '*'
---
Director:
  rules:
    'metatagmanagementfiles//$Action/$ID/$OtherID': 'MetaTagCMSControlFiles'
    'metatagmanagementpages//$Action/$ID/$OtherID': 'MetaTagCMSControlPages'
